tops:
  - cardigan
  - blouse
  - dickey
  - henley
  - polo
  - pullover
  - shell
  - shirt
  - tank
  - tee
  - top
  - tunic
  - sweater
  - sweatshirt
  - vee
  - turtleneck
  - hoodie
  - duster
  - crop top
  - guayabera
  - guernsey
  - halterneck
  - jersey
  - twinset

trousers and shorts:
  - bell-bottoms
  - chaps
  - jodhpurs
  - overall
  - pedal pushers
  - sweatpants
  - windpants
  - chinos
  - pant
  - pants
  - jeans
  - joggers
  - legging
  - leggings
  - stilt
  - trouser
  - trousers
  - short
  - shorts

skirts:
  - skirt
  - miniskirt
  - microskirt
  - sarong
  - skort
  - tutu
  - wrap

dresses:
  - dress
  - gown
  - jumpsuit
  - minidress
  - robe
  - romper
  - shirtdress
  - slip
  - slipdress
  - coatdress
  - formal wear
  - frock
  - jumper
  - sundress

outerwear:
  - jacket
  - parka
  - vest
  - blazer
  - coat
  - peacoat
  - poncho
  - hoodie
  - apron
  - british warm
  - cagoule
  - cape
  - chesterfield
  - gilet
  - overcoat
  - paletot
  - raincoat
  - robe
  - shawl
  - shrug
  - waistcoat
  - windbreaker

underwear:
  - cami
  - camisole
  - bandeau
  - bottoms
  - bra
  - bralette
  - briefs
  - chemise
  - lace
  - panties
  - robe
  - sleepshirt
  - thong
  - bodysuit
  - body suit
  - undershirt
  - diaper
  - slip
  - underpants
  - boxer briefs
  - boxer shorts
  - playsuit
  - teddy

footwear:
  - ankle-wrap platform
  - boots
  - boot
  - bootie
  - booties
  - chukka
  - chukkas
  - clog
  - clogs
  - creeper
  - creepers
  - espadrilles
  - flats
  - flip flop
  - mule
  - loafer
  - oxford
  - oxfords
  - plimsole
  - pump
  - pumps
  - sandal
  - sandals
  - shoe
  - shoes
  - sneaker
  - sneakers
  - wedge
  - hosiery
  - spats
  - slipper
  - sock
  - socks
  - stocking

headwear:
  - fedora
  - hat
  - cap
  - beanie
  - beret
  - helmet
  - hood
  - toque
  - turban
  - veil

nightwear:
  - babydoll
  - blanket sleeper
  - negligee
  - nightgown
  - nightshirt
  - pajamas

swimwear:
  - bikini
  - bikini top
  - bikini bottom
  - bikini bottoms
  - boardshorts
  - dry suit
  - monokini
  - rash guard
  - square leg suit
  - swim briefs
  - swim diaper
  - trunks
  - wetsuit

accessories:
  - belt
  - watch
  - sunglasses
  - neckle
  - necklace
  - earrings
  - earring set
  - bracelet
  - scarf
  - ring
  - headband
  - bandana
  - bow tie
  - coin purse
  - cufflink
  - cummerbund
  - gaiters
  - glasses
  - gloves
  - headband
  - handkerchief
  - muff
  - necktie
  - pocketwatch
  - sash
  - scarf
  - suspenders
  - umbrella
  - wallet
  - wristwatch

bags:
  - backpack
  - bag
  - card case
  - clutch
  - keychain
  - passport holder
  - pouch
  - travel kit
  - tote
  - handbag
  - purse
