jackets:
  - jacket
  - parka
  - vest
  - blazer
  - cardigan
  - coat
  - peacoat
  - poncho

top:
  - blouse
  - cami
  - camisole
  - dickey
  - polo
  - pullover
  - shell
  - shirt
  - tank
  - tee
  - top
  - tunic

sweater:
  - sweater
  - sweatshirt
  - vee
  - turtleneck
  - hoodie
  - duster

dresses:
  - dress
  - gown
  - jumpsuit
  - minidress
  - robe
  - romper
  - shirtdress
  - slip
  - slipdress

pants:
  - chinos
  - pant
  - pants
  - jeans
  - joggers
  - legging
  - leggings
  - stilt
  - trouser
  - trousers

skirt:
  - miniskirt

shorts:
  - short
  - briefs

shoes:
  - ankle-wrap platform
  - boots
  - boot
  - bootie
  - booties
  - chukka
  - chukkas
  - clog
  - clogs
  - creeper
  - creepers
  - espadrilles
  - flats
  - flip flop
  - mule
  - loafer
  - oxford
  - oxfords
  - plimsole
  - pump
  - pumps
  - sandal
  - sandals
  - shoe
  - shoes
  - sneaker
  - sneakers
  - wedge

accessories:
  - belt
  - watch
  - sunglasses
  - neckle
  - necklace
  - earrings
  - earring set
  - bracelet
  - scarf
  - ring
  - headband

bags:
  - backpack
  - bag
  - card case
  - clutch
  - keychain
  - passport holder
  - pouch
  - travel kit
  - tote
  - wallet

underwear:
  - bandeau
  - bikini top
  - bikini bottom
  - bikini bottoms
  - bottoms
  - bra
  - bralette
  - briefs
  - chemise
  - lace
  - panties
  - robe
  - sleepshirt
  - thong
  - socks

bodysuit:
  - body suit

hats:
  - fedora
  - hat
  - cap
  - beanie
