tops:
  - caftan
  - cardigan
  - crop top
  - body
  - blouse
  - dickey
  - duster
  - guayabera
  - guernsey
  - halterneck
  - henley
  - hoodie
  - jersey
  - polo
  - popover
  - pullover
  - overshirt
  - leotard
  - shell
  - shirt
  - tank
  - tee
  - top
  - tunic
  - turtleneck
  - turtle neck
  - twinset
  - sweater
  - sweatshirt
  - vee

trousers and shorts:
  - bell-bottoms
  - chaps
  - chinos
  - jeans
  - jodhpurs
  - joggers
  - leggings
  - pant
  - pedal pushers
  - shorts
  - shortalls
  - skinny
  - stilt
  - sweatpants
  - sweats
  - trouser
  - windpants

skirts:
  - culottes
  - microskirt
  - miniskirt
  - skirt
  - skort
  - tutu
  - wrap

sarong:
  - sarong
  - pareo

overalls:
  - bodysuit
  - body suit
  - shamois suit
  - playsuit
  - jumpsuit
  - romper
  - jumper
  - overall
  - ski suit
  - tri suit
  - top shorts set

dresses:
  - caftan
  - dress
  - gown
  - minidress
  - robe
  - shirtdress
  - slip
  - slipdress
  - coatdress
  - formal wear
  - frock
  - sundress

apron:
  - apron

outerwear:
  - anorak
  - blazer
  - bomber
  - british warm
  - cagoule
  - cape
  - chesterfield
  - coat
  - gilet
  - hoodie
  - jacket
  - overcoat
  - paletot
  - parka
  - raincoat
  - peacoat
  - poncho
  - robe
  - shawl
  - shrug
  - vest
  - waistcoat
  - windbreaker

tights:
  - tights
  - pantyhose
  - leotard
  - tricot

thong:
  - bottoms
  - boxer briefs
  - boxer shorts
  - briefs
  - panties
  - thong
  - underpants

underwear:
  - bandeau
  - bra
  - bralette

  - cami
  - camisole
  - sleepshirt
  - undershirt

  - bodysuit
  - body suit
  - teddy

  - caftan
  - diaper
  - slip
  - chemise
  - lace
  - leotard
  - robe

footwear:
  - ankle-wrap platform
  - boots
  - boot
  - bootie
  - booties
  - chukka
  - clogs
  - creeper
  - derby
  - espadrilles
  - flats
  - flip flop
  - heels
  - hosiery
  - mule
  - mules
  - loafer
  - oxford
  - plimsole
  - pumps
  - runners
  - sandal
  - shoe
  - shoes
  - sneaker
  - spats
  - slides
  - slipper
  - slip-on
  - sock
  - socks
  - stocking
  - toe
  - wedge

headwear:
  - beanie
  - fedora
  - hat
  - cap
  - beanie
  - beret
  - helmet
  - hood
  - toque
  - turban
  - veil

nightwear:
  - babydoll
  - blanket sleeper
  - caftan
  - negligee
  - nightgown
  - nightshirt
  - pajamas

swimwear:
  - bandeau
  - bikini
  - bikini top
  - bikini bottom
  - bikini bottoms
  - boardshorts
  - dry suit
  - maillot
  - monokini
  - rash guard
  - square leg suit
  - swim briefs
  - swim diaper
  - swimsuit
  - trunks
  - wetsuit

# accessories
sunglasses:
  - sunglasses
  - glasses
  - spectacles
  - eyeglasses
  - glass
  - spectacle
  - specs

bracelet:
  - bracelet

earrings:
  - earring
  - earring set
  - stud

necklace:
  - neckle
  - necklace

rings:
  - ring
  - rings

umbrella:
  - umbrella

watch:
  - pocketwatch
  - watch
  - wristwatch

cufflink:
  - cufflink
  - cufflinks
  - cuff links
  - stud
  - studs

cases:
  - iphone case
  - table case
  - computer case

belt:
  - belt
  - strap
  - thong

lipstick:
  - lipstick

blush:
  - blush

accessories other:
  - bandana
  - bow tie
  - coin purse
  - coin belt
  - cravat
  - cummerbund
  - gaiters
  - gloves
  - headband
  - handkerchief
  - muff
  - neckcloth
  - necktie
  - pony holder
  - overlay
  - sash
  - scarf
  - suspenders
  - tie
  - wallet
  - key leash

bags:
  - backpack
  - bag
  - briefcase
  - card case
  - carpetbag
  - case
  - clutch
  - gripsack
  - handbag
  - haversack
  - keychain
  - kitbag
  - knapsack
  - passport holder
  - pack
  - portmanteau
  - pouch
  - purse
  - saddlebag
  - satchel
  - suitcase
  - tote
  - travel kit
  - trunk
  - valise
  - weekender
