tops:
  - cardigan
  - crop top
  - body
  - bodysuit
  - blouse
  - dickey
  - duster
  - guayabera
  - guernsey
  - halterneck
  - henley
  - hoodie
  - jersey
  - polo
  - popover
  - pullover
  - leotard
  - shell
  - shirt
  - tank
  - tee
  - top
  - tunic
  - turtleneck
  - turtle neck
  - twinset
  - sweater
  - sweatshirt
  - vee

trousers and shorts:
  - bell-bottoms
  - chaps
  - jodhpurs
  - overall
  - pedal pushers
  - sweatpants
  - windpants
  - chinos
  - pant
  - pants
  - jeans
  - joggers
  - legging
  - leggings
  - stilt
  - trouser
  - trousers
  - short
  - shorts
  - sweats

skirts:
  - skirt
  - miniskirt
  - microskirt
  - sarong
  - skort
  - tutu
  - wrap

dresses:
  - dress
  - gown
  - jumpsuit
  - minidress
  - robe
  - romper
  - shirtdress
  - slip
  - slipdress
  - coatdress
  - formal wear
  - frock
  - jumper
  - sundress

outerwear:
  - anorak
  - apron
  - blazer
  - british warm
  - cagoule
  - cape
  - chesterfield
  - coat
  - gilet
  - hoodie
  - jacket
  - overcoat
  - paletot
  - parka
  - raincoat
  - peacoat
  - poncho
  - robe
  - shawl
  - shrug
  - vest
  - waistcoat
  - windbreaker

underwear:
  - cami
  - camisole
  - bandeau
  - bottoms
  - bra
  - bralette
  - briefs
  - chemise
  - lace
  - leotard
  - panties
  - robe
  - sleepshirt
  - thong
  - bodysuit
  - body suit
  - undershirt
  - diaper
  - slip
  - underpants
  - boxer briefs
  - boxer shorts
  - playsuit
  - teddy

footwear:
  - ankle-wrap platform
  - boots
  - boot
  - bootie
  - booties
  - chukka
  - clog
  - clogs
  - creeper
  - creepers
  - espadrilles
  - flats
  - flip flop
  - hosiery
  - mule
  - loafer
  - loafers
  - oxford
  - oxfords
  - plimsole
  - pump
  - pumps
  - sandal
  - sandals
  - shoe
  - shoes
  - sneaker
  - sneakers
  - spats
  - slides
  - slipper
  - slippers
  - sock
  - socks
  - stocking
  - wedge
  - wedges

headwear:
  - fedora
  - hat
  - cap
  - beanie
  - beret
  - helmet
  - hood
  - toque
  - turban
  - veil

nightwear:
  - babydoll
  - blanket sleeper
  - negligee
  - nightgown
  - nightshirt
  - pajamas

swimwear:
  - bikini
  - bikini top
  - bikini bottom
  - bikini bottoms
  - boardshorts
  - dry suit
  - maillot
  - monokini
  - rash guard
  - square leg suit
  - swim briefs
  - swim diaper
  - trunks
  - wetsuit

# accessories
sunglasses:
  - sunglasses
  - glasses
  - spectacles
  - eyeglasses
  - glass
  - spectacle
  - specs

bracelet:
  - bracelet

earrings:
  - earrings
  - earring set
  - stud
  - studs

necklace:
  - neckle
  - necklace

rings:
  - ring
  - rings

umbrella:
  - umbrella

watch:
  - pocketwatch
  - watch
  - wristwatch

cufflink:
  - cufflink
  - cufflinks
  - stud
  - studs

accessories other:
  - bandana
  - belt
  - bow tie
  - coin purse
  - cummerbund
  - gaiters
  - gloves
  - headband
  - handkerchief
  - muff
  - necktie
  - tie
  - cravat
  - neckcloth
  - overlay
  - sash
  - scarf
  - suspenders
  - wallet

bags:
  - backpack
  - bag
  - card case
  - carpetbag
  - case
  - clutch
  - gripsack
  - handbag
  - haversack
  - keychain
  - kitbag
  - knapsack
  - passport holder
  - pack
  - portmanteau
  - pouch
  - purse
  - saddlebag
  - satchel
  - suitcase
  - tote
  - travel kit
  - trunk
  - valise
  - weekender
