tops:
  - caftan
  - cardigan
  - crop top
  - body
  - blouse
  - dickey
  - duster
  - guayabera
  - guernsey
  - halterneck
  - henley
  - hoodie
  - jersey
  - polo
  - popover
  - pullover
  - overshirt
  - leotard
  - shell
  - shirt
  - tank
  - tee
  - top
  - tunic
  - turtleneck
  - turtle neck
  - twinset
  - sweater
  - sweatshirt
  - vee

trousers and shorts:
  - bell-bottoms
  - chaps
  - chinos
  - jeans
  - jodhpurs
  - joggers
  - leggings
  - pant
  - pedal pushers
  - shorts
  - shortalls
  - skinny
  - stilt
  - sweatpants
  - sweats
  - trouser
  - windpants

skirts:
  - culottes
  - microskirt
  - miniskirt
  - skirt
  - skort
  - tutu
  - wrap

sarong:
  - sarong
  - pareo

overalls:
  - bodysuit
  - body suit
  - shamois suit
  - playsuit
  - jumpsuit
  - romper
  - jumper
  - overall
  - ski suit
  - tri suit
  - top shorts set

dresses:
  - caftan
  - dress
  - gown
  - minidress
  - robe
  - shirtdress
  - slip
  - slipdress
  - coatdress
  - formal wear
  - frock
  - sundress

apron:
  - apron

outerwear:
  - anorak
  - blazer
  - bomber
  - british warm
  - cagoule
  - cape
  - chesterfield
  - coat
  - gilet
  - hoodie
  - jacket
  - overcoat
  - paletot
  - parka
  - raincoat
  - peacoat
  - poncho
  - robe
  - shawl
  - shrug
  - vest
  - waistcoat
  - windbreaker

tights:
  - tights
  - pantyhose
  - leotard
  - tricot
  - stocking
  - sock
  - hose
  - hosiery

thong:
  - bottoms
  - boxer briefs
  - boxer shorts
  - briefs
  - panties
  - thong
  - underpants

underwear:
  - bandeau
  - bra
  - bralette

  - cami
  - camisole
  - sleepshirt
  - undershirt

  - bodysuit
  - body suit
  - teddy

  - caftan
  - diaper
  - slip
  - chemise
  - lace
  - leotard
  - robe

### ----------------
# Footwear
### ----------------
sandals:
  - sandal

sneakers:
  - sneaker

footwear:
  - ankle-wrap platform
  - boot
  - bootie
  - booties
  - chukka
  - clogs
  - creeper
  - derby
  - espadrilles
  - flats
  - flip flop
  - gaiters
  - heels
  - mule
  - mules
  - loafer
  - oxford
  - plimsole
  - pumps
  - runners
  - shoe
  - spats
  - slides
  - slipper
  - slip-on
  - toe
  - wedge

### ----------------
# Footwear END
### ----------------

### ----------------
# Headwear
### ----------------

ear gear:
  - ear gear

cap:
  - cap

headwear:
  - beanie
  - fedora
  - hat
  - beret
  - helmet
  - hood
  - toque
  - veil

### ----------------
# Headwear END
### ----------------

nightwear:
  - babydoll
  - blanket sleeper
  - caftan
  - negligee
  - nightgown
  - nightshirt
  - pajamas

swimwear:
  - bandeau
  - bikini
  - bikini top
  - bikini bottom
  - bikini bottoms
  - boardshorts
  - dry suit
  - maillot
  - monokini
  - rash guard
  - square leg suit
  - swim briefs
  - swim diaper
  - swimsuit
  - trunks
  - wetsuit

### ----------------
# Accessories
### ----------------

belt:
  - belt
  - coin belt
  - strap
  - thong
  - cummerbund

blush:
  - blush

bracelet:
  - bracelet

card case:
  - card case

cases:
  - iphone case
  - table case
  - computer case

cravat:
  - cravat
  - neckcloth
  - neckerchief
  - handkerchief

cufflink:
  - cufflink
  - cuff links
  - studs

earrings:
  - earring
  - earring set
  - stud

gloves:
  - gloves
  - muff

lipstick:
  - lipstick

necklace:
  - neckle
  - necklace

ring:
  - ring

scrunchie:
  - scrunchy
  - scrunchie
  - pony holder

sunglasses:
  - eyeglasses
  - glass
  - specs
  - spectacle
  - sunglasses

suspenders:
  - suspenders

tie:
  - necktie
  - bow tie
  - tie

turban:
  - turban
  - headband

umbrella:
  - umbrella

wallet:
  - coin purse
  - wallet

watch:
  - pocketwatch
  - watch
  - wristwatch

accessories other:
  - bandana
  - overlay
  - sash
  - scarf
  - key leash

### ----------------
# Accessories END
### ----------------

backpack:
  - backpack
  - bag

bags:
  - bag
  - briefcase
  - carpetbag
  - case
  - clutch
  - gripsack
  - handbag
  - haversack
  - keychain
  - kitbag
  - knapsack
  - passport holder
  - pack
  - portmanteau
  - pouch
  - purse
  - saddlebag
  - satchel
  - suitcase
  - tote
  - travel kit
  - trunk
  - valise
  - weekender

blanket:
  - blanket
